version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:

