version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: devTales
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:

